MvcCoreDemo3/Entities/Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreDemo3.Entities
{
    public class Article
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Category Category { get; set; }
    }
}

MvcCoreDemo3/Entities/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreDemo3.Entities
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual List<Article> Articles { get; set; }
    }
}

MvcCoreDemo3/Models/BlogContex.cs
using Microsoft.EntityFrameworkCore;
using MvcCoreDemo3.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreDemo3.Models
{
    public class BlogContex : DbContext
    {
        public DbSet<Category> Categories { get; set; }
        public DbSet<Article> Articles { get; set; }
        public BlogContex(DbContextOptions<BlogContex> options) : base(options)
        {
            var s = "";
        }
    }
}

MvcCoreDemo3/Models/CategoryListModel.cs
using System.Collections.Generic;
using MvcCoreDemo3.Entities;

namespace MvcCoreDemo3.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
    }
}

MvcCoreDemo3/Models/HomeViewModel.cs
using MvcCoreDemo3.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreDemo3.Models
{
    public class HomeViewModel
    {
        public List<Category> Categories { get; set; }
        public List<Article> Articles { get; set; }
    }
}

MvcCoreDemo3/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MvcCoreDemo3.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [Area("Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MvcCoreDemo3/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MvcCoreDemo3.Controllers
{
    public class CommonController : Controller
    {
        [Route("/error")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MvcCoreDemo3/Controllers/FilterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcCoreDemo3.Filters;
using MvcCoreDemo3.Filters;

namespace MvcCoreDemo3.Controllers
{
    public class FilterController : Controller
    {
        [CustomFilter]
        public IActionResult Index()
        {
            return View();
        }


    }
}

MvcCoreDemo3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcCoreDemo3.Entities;
using MvcCoreDemo3.Filters;
using MvcCoreDemo3.Models;

namespace MvcCoreDemo3.Controllers
{
    public class HomeController : Controller
    {
        public object BlogViewModel { get; private set; }

        public IActionResult Index()
        {
            return View();
        }

        [HandleException(ViewName = "DivideByZero", ExceptionType = typeof(DivideByZeroException))]
        public IActionResult Index2()
        {
            throw new DivideByZeroException();
            return View();
        }
        public IActionResult GetCategory()
        {
            List<Category> categories = new List<Category>();
            categories.Add(new Category { Id = 1, Name = "C#" });
            categories.Add(new Category { Id = 2, Name = "Design Paterns" });
            categories.Add(new Category { Id = 3, Name = "Web Programming" });

            HomeViewModel model = new HomeViewModel();
            model.Categories = categories;
            return View(new CategoryListViewModel
            {
                Categories = categories
            });
        }

    }
}

MvcCoreDemo3/Controllers/SessionDemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MvcCoreDemo3.Controllers
{
    public class SessionDemoController : Controller
    {
        public IActionResult Index()
        {

            if (HttpContext.Session.GetInt32("sayac") == null)
            {
                HttpContext.Session.SetInt32("sayac", 1);
            }
            else
            {
                HttpContext.Session.SetInt32("sayac", (int)HttpContext.Session.GetInt32("sayac") + 1);
            }
            return View();
        }

        public string GetSayac()
        {
            return HttpContext.Session.GetInt32("sayac").ToString();
        }
    }
}

MvcCoreDemo3/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using MvcCoreDemo3.Entities;
using MvcCoreDemo3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreDemo3.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        public ViewViewComponentResult Invoke(string filter)
        {
            List<Category> categories = new List<Category>();
            categories.Add(new Category { Id = 1, Name = "C#" });
            categories.Add(new Category { Id = 2, Name = "Design Paterns" });
            categories.Add(new Category { Id = 3, Name = "Web Programming" });
            categories.Add(new Category { Id = 4, Name = ".net core" });


            var result = new CategoryListViewModel();
            result.Categories = categories.Where(s => s.Name.ToLower().Contains(filter)).ToList();
            return View(result);
        }
    }
}

MvcCoreDemo3/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Admin index</h1>

MvcCoreDemo3/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>




    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/blog-home.css" rel="stylesheet" />



</head>
<body>


    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">
                <h1 class="my-4">
                    Page Heading
                    <small>Secondary Text</small>
                </h1>
      
            

                <div>
                    @RenderBody()
                </div>
    
            
                </div>
                <!-- Pagination -->
                <ul class="pagination justify-content-center mb-4">
                    <li class="page-item">
                        <a class="page-link" href="#">&larr; Older</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Newer &rarr;</a>
                    </li>
                </ul>
            </div>
 
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
        </div>
        <!-- /.container -->
    </footer>
    <!-- Bootstrap core JavaScript -->

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.js"></script>
</body>


</html>

MvcCoreDemo3/Views/Common/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    kötü bişey oldu ya
</body>
</html>

MvcCoreDemo3/Views/Filter/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>MErhaba Filters</h1>

MvcCoreDemo3/Views/Home/Components/CategoryList/Default.cshtml
@model MvcCoreDemo3.Models.CategoryListViewModel


@foreach (var item in Model.Categories)
{

    @item.Name
    <br />
}

MvcCoreDemo3/Views/Home/GetCategory.cshtml
@model MvcCoreDemo3.Models.HomeViewModel

@{
    ViewData["Title"] = "GetCategory";
}

<h1>GetCategory</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Categories) {
    <tr><td>@item.Id </td><td>@item.Name</td></tr>
}
    </tbody>
</table>

MvcCoreDemo3/Views/Home/Index - Copy.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

MvcCoreDemo3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

MvcCoreDemo3/Views/Home/Index2.cshtml
@{
    ViewData["Title"] = "Index2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index2</h1>

MvcCoreDemo3/Views/Shared/Components/CategoryList/Default.cshtml
@model MvcCoreDemo3.Models.CategoryListViewModel


@foreach (var item in Model.Categories)
{

    @item.Name
    <br />
}

MvcCoreDemo3/Views/Shared/DivideByZero.cshtml
@{
    Exception exception = ViewData["HandleException"] as Exception;

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DivideByZero error</title>
</head>
<body>
 
    <h1> @exception.Message</h1>
    <h6>@exception.StackTrace</h6>
</body>
</html>

MvcCoreDemo3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>




    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/blog-home.css" rel="stylesheet" />



</head>
<body>


    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>

                <div>
                    @await Component.InvokeAsync("CategoryList", new { filter = "a" })
                </div>
            </div>
        </div>
    </nav>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">
                <h1 class="my-4">
                    Page Heading
                    <small>Secondary Text</small>
                </h1>
                <!-- Blog Post -->
                <div class="card mb-4">
                    <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                    <div class="card-body">
                        <h2 class="card-title">Post Title</h2>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
                        <a href="#" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                    <div class="card-footer text-muted">
                        Posted on January 1, 2017 by
                        <a href="#">Start Bootstrap</a>
                    </div>
                </div>

                <div>
                    @RenderBody()
                </div>
                <!-- Blog Post -->
                <div class="card mb-4">
                    <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                    <div class="card-body">
                        <h2 class="card-title">Post Title</h2>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
                        <a href="#" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                    <div class="card-footer text-muted">
                        Posted on January 1, 2017 by
                        <a href="#">Start Bootstrap</a>
                    </div>
                </div>
                <!-- Blog Post -->
                <div class="card mb-4">
                    <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                    <div class="card-body">
                        <h2 class="card-title">Post Title</h2>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
                        <a href="#" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                    <div class="card-footer text-muted">
                        Posted on January 1, 2017 by
                        <a href="#">Start Bootstrap</a>
                    </div>
                </div>
                <!-- Pagination -->
                <ul class="pagination justify-content-center mb-4">
                    <li class="page-item">
                        <a class="page-link" href="#">&larr; Older</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Newer &rarr;</a>
                    </li>
                </ul>
            </div>
            <!-- Sidebar Widgets Column -->
            <div class="col-md-4">
                <!-- Search Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Search</h5>
                    <div class="card-body">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-secondary" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>
                <!-- Categories Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Categories</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <ul class="list-unstyled mb-0">
                                    <li>
                                        <a href="#">Web Design</a>
                                    </li>
                                    <li>
                                        <a href="#">HTML</a>
                                    </li>
                                    <li>
                                        <a href="#">Freebies</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-lg-6">
                                <ul class="list-unstyled mb-0">
                                    <li>
                                        <a href="#">JavaScript</a>
                                    </li>
                                    <li>
                                        <a href="#">CSS</a>
                                    </li>
                                    <li>
                                        <a href="#">Tutorials</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Side Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Side Widget</h5>
                    <div class="card-body">
                        You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
        </div>
        <!-- /.container -->
    </footer>
    <!-- Bootstrap core JavaScript -->

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.js"></script>
</body>


</html>